Repository dojo/framework, pull requests merged in 2019-03, with the labels that each got.

#297 Ensure that nodes are inserted in the correct position when nested within widgets
  src/widget-core/vdom.ts
  tests/widget-core/unit/vdom.ts
Labels: bug

#301 Correct links to the i18n guide now there's no longer an index.md
  README.md
  src/i18n/README.md
  src/widget-core/README.md
Labels: reference guide

#290 Enhancement: Do not mutate VNodes or WNodes
  src/widget-core/WidgetBase.ts
  src/widget-core/d.ts
  src/widget-core/interfaces.d.ts
  src/widget-core/registerCustomElement.ts
  src/widget-core/vdom.ts
  tests/routing/unit/Outlet.ts
  tests/stores/unit/StoreProvider.ts
  tests/widget-core/unit/Container.ts
  tests/widget-core/unit/WidgetBase.ts
  tests/widget-core/unit/decorators/beforeRender.ts
  tests/widget-core/unit/decorators/inject.ts
  tests/widget-core/unit/decorators/watch.ts
Labels: breaking change, enhancement
